// <auto-generated />
using GhostOfJoe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhostOfJoe.Migrations
{
    [DbContext(typeof(ServerDataContext))]
    partial class ServerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GhostOfJoe.Models.Categories", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_id")
                        .HasColumnType("Integer");

                    b.Property<bool>("higherBetter")
                        .HasColumnType("Integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("Text");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("Text");

                    b.HasKey("category_id");

                    b.HasIndex("game_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Games", b =>
                {
                    b.Property<int>("game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("server_id")
                        .HasColumnType("Integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("Integer");

                    b.HasKey("game_id");

                    b.HasIndex("server_id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Scores", b =>
                {
                    b.Property<int>("score_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("category_id")
                        .HasColumnType("Integer");

                    b.Property<int>("user_id")
                        .HasColumnType("Integer");

                    b.Property<double>("value")
                        .HasColumnType("Numeric(10,1)");

                    b.HasKey("score_id");

                    b.HasIndex("category_id");

                    b.HasIndex("user_id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Servers", b =>
                {
                    b.Property<ulong>("server_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("safeFlow")
                        .HasColumnType("Integer");

                    b.HasKey("server_id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Titles", b =>
                {
                    b.Property<int>("title_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("Text");

                    b.Property<int>("user_id")
                        .HasColumnType("Integer");

                    b.HasKey("title_id");

                    b.HasIndex("user_id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("discordUser_id")
                        .HasColumnType("Integer");

                    b.Property<ulong>("server_id")
                        .HasColumnType("Integer");

                    b.HasKey("user_id");

                    b.HasIndex("server_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Categories", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Games", "game")
                        .WithMany()
                        .HasForeignKey("game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("game");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Games", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Servers", "Server")
                        .WithMany()
                        .HasForeignKey("server_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Scores", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Categories", "category")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Titles", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Users", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Servers", "Server")
                        .WithMany()
                        .HasForeignKey("server_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });
#pragma warning restore 612, 618
        }
    }
}
