// <auto-generated />
using System;
using GhostOfJoe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhostOfJoe.Migrations
{
    [DbContext(typeof(ServerDataContext))]
    partial class ServerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<bool>("HigherBetter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("higherBetter");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("CategoryId");

                    b.HasIndex("GameId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("GameId");

                    b.HasIndex("ServerId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("NUMERIC (10, 1)")
                        .HasColumnName("value");

                    b.HasKey("ScoreId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Servers", b =>
                {
                    b.Property<ulong>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_id");

                    b.Property<bool>("SafeFlow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("safeFlow");

                    b.HasKey("ServerId");

                    b.ToTable("servers");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Titles", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("title_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("titles");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discordUser_id");

                    b.Property<int?>("PreferredScoreSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferred_score_set_id");

                    b.Property<int?>("PreferredWeightSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferred_weight_set_id");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_id");

                    b.HasKey("UserId");

                    b.HasIndex("PreferredScoreSetId");

                    b.HasIndex("PreferredWeightSetId");

                    b.HasIndex("ServerId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bill_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("short_name");

                    b.HasKey("BillId");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.BillHasMetric", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bill_id");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metric_id");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<int>("ScoreSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_set_id");

                    b.HasIndex("BillId");

                    b.HasIndex("MetricId");

                    b.HasIndex("ScoreSetId");

                    b.ToTable("bill_has_metric");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("gender_id");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name");

                    b.HasKey("GenderId");

                    b.ToTable("gender");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Metric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("metric_id");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name");

                    b.HasKey("MetricId");

                    b.ToTable("metric");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.MetricHasWeight", b =>
                {
                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metric_id");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.Property<int>("WeightSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_set_id");

                    b.HasIndex("MetricId");

                    b.HasIndex("WeightSetId");

                    b.ToTable("metric_has_weights");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.MetricScoreSet", b =>
                {
                    b.Property<int>("ScoreSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_set_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ScoreSetId");

                    b.ToTable("metric_score_set");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.MetricWeightSet", b =>
                {
                    b.Property<int>("WeightSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_set_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("WeightSetId");

                    b.ToTable("metric_weight_set");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("office_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("OfficeId");

                    b.ToTable("office");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("party_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("PartyId");

                    b.ToTable("party");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Querk", b =>
                {
                    b.Property<int>("QuerkId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("querk_id");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name");

                    b.HasKey("QuerkId");

                    b.ToTable("querks");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("RaceId");

                    b.ToTable("race");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Religon", b =>
                {
                    b.Property<int>("ReligonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("religon_id");

                    b.Property<int?>("Name")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name");

                    b.HasKey("ReligonId");

                    b.ToTable("religon");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.RepHasQuerk", b =>
                {
                    b.Property<int>("QuerkId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("querk_id");

                    b.Property<int>("RepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rep_id");

                    b.HasIndex("QuerkId");

                    b.HasIndex("RepId");

                    b.ToTable("rep_has_querk");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Representitive", b =>
                {
                    b.Property<int>("RepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("rep_id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("birth_year");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("FirstElected")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_elected");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<int>("GenderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gender_id");

                    b.Property<string>("Ipa")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ipa");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<int>("Lgbt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lgbt");

                    b.Property<int>("OfficeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("office_id");

                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("party_id");

                    b.Property<string>("Phonetic")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phonetic");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("race_id");

                    b.Property<int>("ReligonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("religon_id");

                    b.HasKey("RepId");

                    b.HasIndex("GenderId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("PartyId");

                    b.HasIndex("RaceId");

                    b.HasIndex("ReligonId");

                    b.ToTable("representitives");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.RepresentitiveHasBill", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bill_id");

                    b.Property<int>("RepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rep_id");

                    b.Property<int>("VoteTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vote_type_id");

                    b.HasIndex("BillId");

                    b.HasIndex("RepId");

                    b.HasIndex("VoteTypeId");

                    b.ToTable("representitive_has_bills");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.VoteType", b =>
                {
                    b.Property<int>("VoteTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("vote_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("VoteTypeId");

                    b.ToTable("vote_type");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Categories", b =>
                {
                    b.HasOne("GhostOfJoe.Models.GameSystem.Game", "Game")
                        .WithMany("Categories")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Game", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Servers", "Servers")
                        .WithMany("Games")
                        .HasForeignKey("ServerId")
                        .IsRequired();

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Score", b =>
                {
                    b.HasOne("GhostOfJoe.Models.GameSystem.Categories", "Categories")
                        .WithMany("Scores")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.Users", "Users")
                        .WithMany("Scores")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Titles", b =>
                {
                    b.HasOne("GhostOfJoe.Models.Users", "Users")
                        .WithMany("Titles")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Users", b =>
                {
                    b.HasOne("GhostOfJoe.Models.VoteDatabase.MetricScoreSet", "PreferredScoreSet")
                        .WithMany("Users")
                        .HasForeignKey("PreferredScoreSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.MetricWeightSet", "PreferredWeightSet")
                        .WithMany("Users")
                        .HasForeignKey("PreferredWeightSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostOfJoe.Models.Servers", "Servers")
                        .WithMany("Users")
                        .HasForeignKey("ServerId")
                        .IsRequired();

                    b.Navigation("PreferredScoreSet");

                    b.Navigation("PreferredWeightSet");

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.BillHasMetric", b =>
                {
                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.MetricScoreSet", "ScoreSet")
                        .WithMany()
                        .HasForeignKey("ScoreSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Metric");

                    b.Navigation("ScoreSet");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.MetricHasWeight", b =>
                {
                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.MetricWeightSet", "WeightSet")
                        .WithMany()
                        .HasForeignKey("WeightSetId")
                        .IsRequired();

                    b.Navigation("Metric");

                    b.Navigation("WeightSet");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.RepHasQuerk", b =>
                {
                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Querk", "Querk")
                        .WithMany()
                        .HasForeignKey("QuerkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Representitive", "Rep")
                        .WithMany()
                        .HasForeignKey("RepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Querk");

                    b.Navigation("Rep");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Representitive", b =>
                {
                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Gender", "Gender")
                        .WithMany("Representitives")
                        .HasForeignKey("GenderId")
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Office", "Office")
                        .WithMany("Representitives")
                        .HasForeignKey("OfficeId")
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Party", "Party")
                        .WithMany("Representitives")
                        .HasForeignKey("PartyId")
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Race", "Race")
                        .WithMany("Representitives")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Religon", "Religon")
                        .WithMany("Representitives")
                        .HasForeignKey("ReligonId")
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Office");

                    b.Navigation("Party");

                    b.Navigation("Race");

                    b.Navigation("Religon");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.RepresentitiveHasBill", b =>
                {
                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.Representitive", "Rep")
                        .WithMany()
                        .HasForeignKey("RepId")
                        .IsRequired();

                    b.HasOne("GhostOfJoe.Models.VoteDatabase.VoteType", "VoteType")
                        .WithMany()
                        .HasForeignKey("VoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Rep");

                    b.Navigation("VoteType");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Categories", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GhostOfJoe.Models.GameSystem.Game", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Servers", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.Users", b =>
                {
                    b.Navigation("Scores");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Gender", b =>
                {
                    b.Navigation("Representitives");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.MetricScoreSet", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.MetricWeightSet", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Office", b =>
                {
                    b.Navigation("Representitives");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Party", b =>
                {
                    b.Navigation("Representitives");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Race", b =>
                {
                    b.Navigation("Representitives");
                });

            modelBuilder.Entity("GhostOfJoe.Models.VoteDatabase.Religon", b =>
                {
                    b.Navigation("Representitives");
                });
#pragma warning restore 612, 618
        }
    }
}
